version = 0.1

[default.deploy.parameters]
stack_name = "sam-upnest2"
resolve_s3 = true
s3_prefix = "sam-upnest2"
region = "eu-south-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Stage\""
image_repositories = []
