version = 0.1

[staging.deploy.parameters]
stack_name = "sam-upnest2"
resolve_s3 = true
s3_prefix = "sam-upnest2"
region = "eu-south-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"staging\""
image_repositories = []

[stage-env.deploy.parameters]
stack_name = "sam-upnest"
resolve_s3 = true
s3_prefix = "sam-upnest"
region = "eu-south-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
